### ISSUE TITLE
integers aren't webscale

### ISSUE THREAD

**Issue by hikari-no-yume** [igorw/dev-zero#1]
should produce floats

**Comment by igorw** [comment]
-1 does not float my boat

**Comment by hikari-no-yume** [comment]
hmm, how about `"0"` because that's text, text is web, web is web scale

**Comment by igorw** [comment]
turns out that this library is immutable, it has been cartographically sealed

**Comment by hikari-no-yume** [comment]
cartographically?

**Comment by igorw** [comment]
yea they got some pretty strong carto algos

**Comment by toverux** [comment]
But does it shards?

**Comment by hikari-no-yume** [comment]
clearly we need a distributed system with load balancing and threading

**Comment by toverux** [comment]
-1 avoid threading, not everyone has a thread-safe distribution of PHP.
Instead, what about a libuv backend asynchronously connecting to MongoDB instances full of zeros? [Mongo is webscale](http://www.mongodb-is-web-scale.com/)!

**Comment by hikari-no-yume** [comment]
we need HHVM support, for Facebook Scale

**Comment by toverux** [comment]
+1
We should also use `<script language="php">`. As you know, it makes PHP 50x faster.

**Comment by hikari-no-yume** [comment]
-1 not webscale, unsupported by PHP 7
